# Generated by Django 3.1.2 on 2020-10-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='mobile',
            new_name='mob',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='name',
        ),
    ]
